#define WRITEBYTE(WORD,SBITPOS,BYTE) (WORD=(WORD&~(255<<SBITPOS))|(BYTE<<SBITPOS))
#define WRITENIBBLE(WORD,SBITPOS,NIBBLE) (WORD=(WORD&~(15<<SBITPOS))|(NIBBLE<<SBITPOS))
#define READBIT(WORD,BIT)  ((WORD>>BIT)&1)
#define READNIBBLE(WORD,NIBBLESTARTBIT) ((WORD>>NIBBLESTARTBIT)&15)

